var faIcons = [
  { "title": "fas fa-play", "searchTerms": [] },
  { "title": "fas fa-pause", "searchTerms": [] },
  { "title": "fas fa-stop", "searchTerms": [] },
  { "title": "fas fa-step-backward", "searchTerms": [] },
  { "title": "fas fa-step-forward", "searchTerms": [] },
  { "title": "fas fa-volume-down", "searchTerms": [] },
  { "title": "fas fa-volume-up", "searchTerms": [] },
  { "title": "fas fa-volume-mute", "searchTerms": [] },
  { "title": "fas fa-volume-off", "searchTerms": [] },
  { "title": "fas fa-lock", "searchTerms": [] },
  { "title": "fas fa-unlock-alt", "searchTerms": [] },
  { "title": "fas fa-info-circle", "searchTerms": [] },
  { "title": "fas fa-home", "searchTerms": [] },
  { "title": "fas fa-wifi", "searchTerms": [] },
  { "title": "fas fa-power-off", "searchTerms": [] },
  { "title": "fas fa-cog", "searchTerms": [] },
  { "title": "fas fa-lightbulb", "searchTerms": [] },
  { "title": "fas fa-bolt", "searchTerms": [] },
  { "title": "fas fa-battery-quarter", "searchTerms": [] },
  { "title": "fas fa-battery-half", "searchTerms": [] },
  { "title": "fas fa-battery-three-quarters", "searchTerms": [] },
  { "title": "fas fa-battery-full", "searchTerms": [] },
  { "title": "fas fa-list", "searchTerms": [] },
  { "title": "fas fa-music", "searchTerms": [] }
];
